# Site settings
title: Binary Ruminations Mumble
email:
description:
baseurl: "/mumble/"
url: "http://binaryruminations.com" # the base hostname & protocol for your site
twitter_username:
github_username: dogonthehorizon

# Build settings
markdown: kramdown
